theme: minima
instagram_username: minnix_xinniw
spotify_username: xinniw
youtube_channel: UCV75fqpnnjCmM0I7Fogf53w
description: ambient, techno, future music
facebook_username: xinniw.minnix
booking_message: 'for booking contact: minnix.xinniw@gmail.com'
title: xinniw
plugins:
  - jekyll-feed
rss: 'xinniw feed'
google_analytics: 'UA-154118349-1'